language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
sudo: false
env:
matrix:
  include:
    - python: "2.7"
      env: PLONE_VERSION=4.3.x
    - python: "2.7"
      env: PLONE_VERSION=5.0.x
    - python: "2.7"
      env: PLONE_VERSION=5.1.x
    - python: "2.7"
      env: PLONE_VERSION=5.2.x
    - python: "3.6"
      env: PLONE_VERSION=5.2.x
    - python: "3.7"
      env: PLONE_VERSION=5.2.x
      dist: xenial
      sudo: true
  fast_finish: true
cache:
  pip: true
  directories:
    - $HOME/buildout-cache
before_install:
  - mkdir -p $HOME/buildout-cache/{eggs,downloads}
  - mkdir $HOME/.buildout
  - echo "[buildout]" > $HOME/.buildout/default.cfg
  - echo "download-cache = $HOME/buildout-cache/downloads" >> $HOME/.buildout/default.cfg
  - echo "eggs-directory = $HOME/buildout-cache/eggs" >> $HOME/.buildout/default.cfg
  - pip install zc.buildout
  - sed -ie "s#test-x.x.x.cfg#test-$PLONE_VERSION.cfg#" buildout.cfg
install:
  - buildout -N -t 3 annotate
  - buildout -N -t 3
script:
  - bin/code-analysis
  - bin/test
after_success:
  - bin/createcoverage -d 'htmlcov'
  - pip install -q coveralls
  - coveralls
notifications:
  irc: irc.freenode.org#plone-testing
